name: iOS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Resolve Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild \
          -scheme maciOS \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          CODE_SIGNING_ALLOWED=NO \
          clean build
